#!/usr/bin/env node
'use strict';

// Compile with SwitchyOmega's own omega-pac engine, not a rule translation.
// The vendored compiler is from the official v2.5.20 XPI (GPL-3.0-or-later).
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const vm = require('node:vm');

function expand(filename) {
    return filename.startsWith('~/') ? path.join(os.homedir(), filename.slice(2)) : filename;
}

function loadCompiler() {
    const context = vm.createContext({});
    vm.runInContext(fs.readFileSync(path.join(__dirname, 'vendor', 'omega_pac.min.js'), 'utf8'),
                    context, {filename: 'omega_pac.min.js'});
    return context.OmegaPac;
}

function proxySpec(value) {
    const url = new URL(value);
    const scheme = url.protocol.slice(0, -1);
    if (!['http', 'https', 'socks4', 'socks5'].includes(scheme) || !url.hostname ||
        url.username || url.password || url.search || url.hash || (url.pathname && url.pathname !== '/')) {
        throw new Error('Proxy must be http/https/socks4/socks5://host:port without credentials or a path');
    }
    const port = Number(url.port || ({http: 80, https: 443}[scheme]));
    if (!Number.isInteger(port) || port < 1 || port > 65535) {
        throw new Error('Proxy port must be between 1 and 65535');
    }
    return {scheme, host: url.hostname, port};
}

function compile(options, {profile, proxy, overrides = []} = {}) {
    if (options.schemaVersion !== 2) {
        throw new Error('Expected SwitchyOmega schemaVersion 2');
    }
    if (!proxy) {
        throw new Error('An explicit proxy URL is required');
    }
    // Do not mutate the export supplied by the caller.
    options = structuredClone(options);
    const switches = Object.values(options).filter(p => p && p.profileType === 'SwitchProfile');
    profile ||= options['-startupProfileName'] || (switches.length === 1 ? switches[0].name : null);
    if (!profile || !options['+' + profile]) {
        throw new Error('Select an existing profile with --profile');
    }
    const fixed = options['+proxy'];
    if (!fixed || fixed.profileType !== 'FixedProfile') {
        throw new Error('Expected a FixedProfile named "proxy" in the export');
    }
    const spec = proxySpec(proxy);
    fixed.fallbackProxy = spec;
    fixed.proxyForHttp = spec;
    fixed.proxyForHttps = spec;
    fixed.proxyForFtp = spec;
    if (!Array.isArray(overrides)) {
        throw new Error('Overrides must be an ordered JSON array of {domain, profile}');
    }
    if (overrides.length) {
        const selected = options['+' + profile];
        if (selected.profileType !== 'SwitchProfile') {
            throw new Error('Local overrides require a SwitchProfile');
        }
        const localRules = [];
        for (const rule of overrides) {
            if (typeof rule.domain !== 'string' || !rule.domain.trim() ||
                /[\s\/:*?#\[\]]/.test(rule.domain) ||
                (rule.profile !== 'direct' && !options['+' + rule.profile])) {
                throw new Error('Each override needs a hostname and an existing result profile (or direct)');
            }
            const domain = rule.domain.toLowerCase().replace(/\.$/, '');
            for (const pattern of [domain, '*.' + domain]) {
                localRules.push({condition: {conditionType: 'HostWildcardCondition', pattern},
                                 profileName: rule.profile});
            }
        }
        selected.rules = localRules.concat(selected.rules || []);
    }
    const compiler = loadCompiler();
    // No "missing profile => DIRECT" fallback: errors must be visible.
    const ast = compiler.PacGenerator.script(options, profile);
    const script = compiler.PacGenerator.ascii(ast.print_to_string({beautify: true}));
    return {profile, script: '// SwitchyOmega native PAC; generated by omega_native.cjs\n' + script + '\n'};
}

function main(argv) {
    const args = {};
    for (let i = 0; i < argv.length; ++i) {
        if (argv[i] === '--help') {
            console.log('Usage: node omega_native.cjs --source /path/to/OmegaOptions.bak [--profile "auto switch"]\n' +
                        '       --proxy socks5://127.0.0.1:your-port [--overrides overrides.json] --output proxy.pac');
            return;
        }
        const name = argv[i];
        if (!['--source', '--profile', '--proxy', '--overrides', '--output'].includes(name) ||
            !argv[i + 1] || argv[i + 1].startsWith('--')) {
            throw new Error('Unknown or incomplete argument: ' + name);
        }
        args[name.slice(2)] = argv[++i];
    }
    if (!args.output) throw new Error('--output is required');
    if (!args.source) throw new Error('--source is required');
    if (!args.proxy) throw new Error('--proxy is required');
    const source = expand(args.source);
    const options = JSON.parse(fs.readFileSync(source, 'utf8'));
    const overrides = args.overrides ? JSON.parse(fs.readFileSync(expand(args.overrides), 'utf8')) : [];
    const result = compile(options, {...args, overrides});
    const output = path.resolve(expand(args.output));
    fs.mkdirSync(path.dirname(output), {recursive: true});
    const temporary = output + '.' + process.pid + '.tmp';
    try {
        fs.writeFileSync(temporary, result.script, {mode: 0o600});
        fs.renameSync(temporary, output);
    } finally {
        fs.rmSync(temporary, {force: true});
    }
    console.log('Native PAC: ' + result.profile + ' -> ' + output + ' (' + result.script.length + ' bytes)');
}

module.exports = {compile};
if (require.main === module) {
    try { main(process.argv.slice(2)); }
    catch (error) { console.error('omega_native: ' + error.message); process.exitCode = 1; }
}
